# general parameters
seed: 42
experiment: debug_snn

# task parameters
task:
  type: plane
  params:
    max_episode_steps: 200
    render: false
    moving_target: 0.0

# general parameters
general:
  model:
    params:
      hidden_dim: 256
      repeat_input: 5
      out_style: last
      dt: 0.004
      flif_kwargs:
        train_V_tau: False
        train_I_tau: False
      readout_kwargs:
        train_V_tau: False
        train_I_tau: False
  optim:
    type: adam
    params:
      lr: 0.0005
  learning:
    params:
      batch_size: 1_024
      n_batches: 30
      unroll_steps: 8
      warmup_steps: 8
      max_norm: 10.0

# policy model parameters
policy:
  model:
    type: FFSNNPB
    params:
      flif_kwargs:
        recurrent: False
  learning:
    params:
      beta: 0.0
      deterministic_transition: False

# transition model parameters
transition:
  model:
    type: RSNNPB

# training parameters
memory_size: 3_000
total_env_steps: 2_000
episodes_per_iteration: 10
evaluate: True
evaluate_every_n_iterations: 25

# plotting parameters
animate: False
record_every_n_iterations: 25
record_first_n_episodes: 5

# logging parameters
project: ann-control
entity: jhuebotter
