# general parameters
seed: 42
experiment: debug

# task parameters
task: plane
env_steps: 200
render: false

# model parameters
memory_size: 1_000
policy:
  model:
    type: MLPPB
    params:
      act_func: 'lrelu'
      hidden_dim: 128
  optim:
    type: adam
    params:
      lr: 0.001
transition:
  model:
    type: GRUPB
    params:
      act_func: 'lrelu'
      hidden_dim: 128
  optim:
    type: adam
    params:
      lr: 0.001

# training parameters
total_env_steps: 4_000
episodes_per_iteration: 2
updates_per_iteration: 2
batch_size: 256
beta: 0.0
unroll_steps: 20
warmup: 30
record_every_n_iterations: 1
record_first_n_episodes: 2

# logging parameters
project: ann-control
entity: jhuebotter