# general parameters
seed: 42
experiment: debug
evaluate: True

# task parameters
task:
  type: plane
  params:
    max_episode_steps: 200
    render: false
    moving_target: 0.0

# general parameters
general:
  learning:
    params:
      batch_size: 1_024
      n_batches: 30
      warmup_steps: 8
      max_norm: 1.0

# policy model parameters
policy:
  model:
    type: MLPPBadapt
    params:
      act_func: lrelu
      hidden_dim: 256
  optim:
    type: adam
    params:
      lr: 0.0005
  learning:
    params:
      unroll_steps: 5
      deterministic_transition: True
      beta: 0.0

# transition model parameters
transition:
  model:
    type: GRUPBadapt
    params:
      act_func: lrelu
      hidden_dim: 256
  optim:
    type: adam
    params:
      lr:  0.0005
  learning:
    params: null

# training parameters
memory_size: 3_000
total_env_steps: 4_000
episodes_per_iteration: 10

# plotting parameters
animate: False
record_every_n_iterations: 25
record_first_n_episodes: 5

# logging parameters
project: ann-control
entity: jhuebotter
