# general parameters
seed: 777
experiment: dev_ann_baseline

# task parameters
task:
  type: reacher2
  params:
    max_episode_steps: 200
    render: false
    moving_target: 0.0

# general parameters
general:
  model:
    params:
      hidden_dim: 512
  optim:
    type: adam
    params:
      lr: 0.0005
  learning:
    params:
      batch_size: 512
      n_batches: 25
      max_norm: 30
      warmup_steps: 5

# policy model parameters
policy:
  model:
    type: rnnPBadapt
    params:
      activation_kwargs:
        act_fn: lrelu
      num_rec_layers: 0
      num_ff_layers: 2
  learning:
    params:
      unroll_steps: 20
      deterministic_transition: True
      beta: 0.0

# transition model parameters
transition:
  model:
    type: rnnPBadapt
    params:
      activation_kwargs:
        act_fn: lrelu
      num_rec_layers: 1
      num_ff_layers: 1
  learning:
    params:
      autoregressive: False
      unroll_steps: 1

# training parameters
memory_size: 1_000
total_env_steps: 500_000
episodes_per_iteration: 25
evaluate: True
evaluate_every_n_iterations: 1
deterministic_action: True

# plotting parameters
animate: False
animate_unroll: 20
record_every_n_iterations: 20
record_first_n_episodes: 5

# logging parameters
project: ann-control
entity: jhuebotter