# general parameters
seed: 42
experiment: debug

# task parameters
task: plane
env_steps: 200
render: false

# model parameters
policy:
  model:
    type: MLPPB
    params:
      act_func: 'lrelu'
      hidden_dim: 128
  optim:
    type: adam
    params:
      lr: 0.001
transition:
  model:
    type: GRUPB
    params:
      act_func: 'lrelu'
      hidden_dim: 128
  optim:
    type: adam
    params:
      lr: 0.001

# training parameters
memory_size: 1_024
total_env_steps: 2_000_000
episodes_per_iteration: 10
updates_per_iteration: 10
batch_size: 1_024
beta: 0.0
unroll_steps: 20
warmup: 30
record_every_n_iterations: 20
record_first_n_episodes: 6

# logging parameters
project: ann-control
entity: jhuebotter