# general parameters
seed: 42
experiment: debug_snn
evaluate: True

# task parameters
task:
  type: plane
  params:
    max_episode_steps: 200
    render: false
    moving_target: 0.0

# policy model parameters
policy:
  model:
    type: FFSNNPB
    params:
      hidden_dim: 256
      repeat_input: 5
      dt: 0.004
  optim:
    type: adam
    params:
      lr: 0.0005
  learning:
    params:
      batch_size: 1_024
      n_batches: 3
      warmup_steps: 8
      unroll_steps: 5
      max_norm: 1.0
      deterministic_transition: True
      flif_kwargs:
        recurrent: False

# transition model parameters
transition:
  model:
    type: RSNNPB
    params:
      hidden_dim: 256
      repeat_input: 5
      dt: 0.004
  optim:
    type: adam
    params:
      lr:  0.0005
  learning:
    params:
      batch_size: 1_024
      n_batches: 1
      warmup_steps: 8
      max_norm: 1.0
      beta: 0.0

# training parameters
memory_size: 3_000
total_env_steps: 4_000
episodes_per_iteration: 10

# plotting parameters
animate: False
record_every_n_iterations: 25
record_first_n_episodes: 5

# logging parameters
project: ann-control
entity: jhuebotter
