# general parameters
seed: 42
experiment: dev_transition_snn

# task parameters
task:
  type: reacher2
  params:
    max_episode_steps: 200
    render: false
    moving_target: 0.0

# general parameters
general:
  model:
    params:
      hidden_dim: 256
  optim:
    type: adam
    params:
      lr: 0.0005
  learning:
    params:
      batch_size: 1_024
      n_batches: 10
      unroll_steps: 5
      warmup_steps: 5
      max_norm: 50

# policy model parameters
policy:
  model:
    type: rnnPBadapt
    params:
      activation_kwargs:
        act_fn: default
      num_rec_layers: 0
      num_ff_layers: 2
  learning:
    params:
      deterministic_transition: False
      beta: 0.0

# transition model parameters
transition:
  model:
    type: RSNNcs
    params:
      hidden_dim: 256
      num_rec_layers: 1
      num_ff_layers: 1
      repeat_input: 8
      out_style: last
      dt: 0.002
      lowerBoundL2Strength: 0.0
      upperBoundL2Strength: 1.0
      weightL2Strength: 0.0
      connection_dims: 0
      nu: 50
      activation_kwargs:
        act_fn: sigmoidspike
        beta: 100.0
      flif_kwargs:
        reset: sub
        # train_V_tau: True
        # train_I_tau: True
      readout_kwargs:
        # train_V_tau: True
        # train_I_tau: False
        n_pop: 50
  optim:
    type: smorms3
    params:
      lr: 0.0005

# training parameters
memory_size: 2_000
total_env_steps: 4_000
episodes_per_iteration: 10
evaluate: True
evaluate_every_n_iterations: 1

# plotting parameters
animate: False
animate_unroll: 5
record_every_n_iterations: 20
record_first_n_episodes: 5

# logging parameters
project: ann-control
entity: jhuebotter
