# general parameters
seed: 777
experiment: dev_double_snn_baseline4

# task parameters
task:
  type: reacher2
  params:
    max_episode_steps: 200
    render: false
    moving_target: 0.0

# general parameters
general:
  model:
    params:
      hidden_dim: 1024
      dt: 0.002
      nu: 100
      out_style: last
      lowerBoundL2Strength: 0.0
      upperBoundL2Strength: 1.0
      weightL2Strength: 0.0
      repeat_input: 8
      activation_kwargs:
        act_fn: sigmoidspike
        beta: 25.0
        gamma: 1.0
      flif_kwargs:
        reset: sub
      readout_kwargs:
        n_pop: 25
  optim:
    type: smorms3
    params:
      lr: 0.0005
  learning:
    params:
      batch_size: 512
      n_batches: 25
      max_norm: 30
      warmup_steps: 5

# policy model parameters
policy:
  model:
    type: RSNNcs
    params:
      num_rec_layers: 0
      num_ff_layers: 2
      connection_dims: 0
  learning:
    params:
      unroll_steps: 20
      deterministic_transition: True

# transition model parameters
transition:
  model:
    type: RSNNcs
    params:
      num_rec_layers: 1
      num_ff_layers: 1
      connection_dims: 0
  learning:
    params:
      autoregressive: False
      unroll_steps: 1

# training parameters
memory_size: 1_000
total_env_steps: 400_000
episodes_per_iteration: 25
evaluate: True
evaluate_every_n_iterations: 1
deterministic_action: False
load_baseline_policy: False
load_baseline_transition: False

# plotting parameters
animate: True
animate_unroll: 20
record_every_n_iterations: 20
record_first_n_episodes: 5

# logging parameters
project: ann-control
entity: jhuebotter
