# general parameters
seed: 42
experiment: dev_ann

# task parameters
task:
  type: reacher2
  params:
    max_episode_steps: 200
    render: false
    moving_target: 0.0

# general parameters
general:
  model:
    params:
      hidden_dim: 256
  optim:
    type: adam
    params:
      lr: 0.0005
  learning:
    params:
      batch_size: 1_024
      n_batches: 100
      max_norm: 30

# policy model parameters
policy:
  model:
    type: rnnPBadapt
    params:
      activation_kwargs:
        act_fn: lrelu
      num_rec_layers: 0
      num_ff_layers: 2
  learning:
    params:
      unroll_steps: 10
      warumup_steps: 8
      deterministic_transition: False
      beta: 0.0

# transition model parameters
transition:
  model:
    type: rnnPBadapt
    params:
      activation_kwargs:
        act_fn: lrelu
      num_rec_layers: 1
      num_ff_layers: 1
  learning:
    params:
      autoregressive: False
      unroll_steps: 20
      warumup_steps: 8

# training parameters
memory_size: 3_000
total_env_steps: 400_000
episodes_per_iteration: 20
evaluate: True
evaluate_every_n_iterations: 10

# plotting parameters
animate: True
animate_unroll: 30
record_every_n_iterations: 10
record_first_n_episodes: 5

# logging parameters
project: ann-control
entity: jhuebotter