# general parameters
seed: 42
experiment: dev_double_snn

# task parameters
task:
  type: reacher2
  params:
    max_episode_steps: 200
    render: false
    moving_target: 0.0

# general parameters
general:
  model:
    params:
      hidden_dim: 512
      dt: 0.002
      nu: 50
      out_style: last
      lowerBoundL2Strength: 0.0
      upperBoundL2Strength: 1.0
      weightL2Strength: 0.0
      repeat_input: 8
      activation_kwargs:
        act_fn: sigmoidspike
        beta: 100.0
      flif_kwargs:
        reset: sub
      readout_kwargs:
        n_pop: 50
  optim:
    type: smorms3
    params:
      lr: 0.0005
  learning:
    params:
      batch_size: 512
      n_batches: 100
      max_norm: 50
      warmup_steps: 8

# policy model parameters
policy:
  model:
    type: RSNNcs
    params:
      num_rec_layers: 0
      num_ff_layers: 2
      connection_dims: 0
  learning:
    params:
      unroll_steps: 20
      deterministic_transition: True

# transition model parameters
transition:
  model:
    type: RSNNcs
    params:
      num_rec_layers: 1
      num_ff_layers: 1
      connection_dims: 0
  learning:
    params:
      autoregressive: True
      unroll_steps: 1

# training parameters
memory_size: 2_000
total_env_steps: 200_000
episodes_per_iteration: 25
evaluate: True
evaluate_every_n_iterations: 1
deterministic_action: True

# plotting parameters
animate: False
animate_unroll: 20
record_every_n_iterations: 20
record_first_n_episodes: 5

# logging parameters
project: ann-control
entity: jhuebotter
